### ISSUE TITLE
Pas clair de ce que sera l'action, après choix des centres, quand un RDV aura été trouvé

### ISSUE THREAD

**Issue by Cuervino** [dunglas/vaccin.click#11]
1. Le site https://vaccin.click/ détaille bien la mise en place de l'alerte.
Cependant, une fois que les centres ont été rajoutés, quelle est l'action proposée par l'extension ? (Dans le cas où l'on ne veut pas de prise de rdv automatique, mais uniquement une alerte)
- Alarme sonore automatique ? 
- Notification à l'écran?
- Si un rdv est trouvé, j'aurais un onglet qui s'ouvre automatiquement ? Quid si jamais ça n'est pas FF en focus sur mon ordi?

2. Je cherche à simuler ce que j'aurais à faire quand un rdv sera trouvé. Donc je mets plein de centre pour connaitre le comportement de l'extension quand le rdv sera trouvé. Pour vérifier que je ne fais pas confiance à l'outil pour rien. Ca marche, mais à mon sens la notification d'une simple ouverture d'onglet n'est pas suffisante, notamment car j'ai l'impression que le focus ne passe pas sur le nouvel onglet. Une alarme sonore complémentaire serait souhaitable.

**Comment by Ubiquite** [comment]
J'ai la même question quand on sélectionne "Réserver automatiquement".
Qu'est ce qu'il se passe ? On recoit juste un email de doctolib confirmant le rdv ?

En tout cas excellente initiative cette extension.

**Comment by dunglas** [comment]
Pour l'instant c'est simplement un onglet qui est ouvert effectivement. Une alarme sonore est une bonne idée ! Ça ne devrait pas être top compliqué à rajouter.

Quand on sélectionne "réserver automatiquement" deux cas de figures :

1. Soit ça marche et on reçoit un mail de Doctolib, et un onglet permettant de publier un Tweet disant que l'extension a trouvé un RDV s'ouvre automatiquement
2. Soit il y a un problème, dans ce cas là l'onglet de réservation s'ouvre (comme en mode non automatique) pour permettre de finir la réservation à la main

Si le cas de 2 arrive, ça serait top de donner les informations de déboggage (en particulier l'URL du centre) pour pouvoir améliorer l'extension et supporter les cas exotiques.

**Comment by edouardflowasia** [comment]
Je viens d'avoir la cas 2 trois fois de suite sur des centres différents, les RDV sont pris avant que l'extension ne fasse la réservation.
