### ISSUE TITLE
Recherche seulement toutes les 3 minutes?

### ISSUE THREAD

**Issue by Cuervino** [dunglas/vaccin.click#12]
je cherche à connaitre la fréquence de recherche. 
J'ai vu une référence à "toutes les 3 minutes" dans une issue
Toutes les 3 minutes est à mon sens trop long, dans ce use case on est à l'échelle de la poignée de seconde. 
J'ai mis un grand nombre de centres (pour tests), j'ai bien des onglets qui s'ouvrent parfois, mais les créneaux sont irrémédiablement déjà pris. Je soupçonne que le délai soit trop long.

**Comment by dunglas** [comment]
Pour l'instant c'est effectivement toutes les trois minutes. On pourrait augmenter la fréquence mais j'ai peur que ça charge trop les serveurs de @doctolib et que ça fasse tomber leur service sous la charge.

On pourrait rajouter une option permettant de configurer la fréquence, mais j'ai peur que le faire trop souvent soit contre-productif (si ça casse Doctolib, plus personne ne peut réserver...).

**Comment by Cuervino** [comment]
Oui, effectivement...
Difficile de savoir où se situe le juste milieu. 
Je pense que 3 minutes est trop long, car les rendez-vous seront toujours pris avant par quelqu'un ciblant un centre en particulier.

Comment cela fonctionne : chaque centre est individuellement checké toutes les 3 minutes, indépendamment des autres, ou bien c'est le rolling check de la liste des centres qui est lancé toute les 3 minutes?

**Comment by dunglas** [comment]
Chaque centre est testé 3 minutes après la fin du test précédent, indépendamment des autres.

**Comment by Cuervino** [comment]
Bon, j'ai testé avec 30 * 1000 millisecondes à la place de 3 * 60 * 1000 ms, et de toute façon le serveur Doctolib nous renvoie un "erreur 429 Too Many Requests".

Sinon, pour la 1ère fois, j'ai pu faire une grande partie du tunnel de résa, les horaires ne me correspondaient pas, mais à cette 10ème tentative (environ), ça aurait pu marcher ! 👍

**Comment by pirquessa** [comment]
> Chaque centre est testé 3 minutes après la fin du test précédent, indépendamment des autres.

> Bon, j'ai testé avec 30 * 1000 millisecondes à la place de 3 * 60 * 1000 ms, et de toute façon le serveur Doctolib nous renvoie un "erreur 429 Too Many Requests".

J'ai aussi beaucoup de centres à check sur Paris. Sans trop de succès pour le moment. Effectivement en faisant un peu de debug il ne peut jamais check toute la liste puisque les derniers calls sont tous en 429... Il faudrait une queue de calls, qui se vide toutes les X ms, pour spammer Doctolib mais pas tout à la fois...

C'est compliqué d'installer un env pour dev une extension ? J'pourrais voir de participer un peu :)

Merci pour l'initiative !

**Comment by Cuervino** [comment]
Je pensais que c'était simple de modifier les fichiers d'une extension, donc j'ai bêtement récupérer le xpi dans le dossier des extensions, je l'ai renommé en zip, puis j'ai fait des modifs manuelles.

Je me suis rendu compte que chaque extension devait être signée pour éviter les corruptions, et donc la parade a été d'utiliser `Firefox Developer Edition`.

Avec ce logiciel, c'est possible de charger localement une extension non signée.
![image](https://user-images.githubusercontent.com/28654802/118845890-76beff80-b8cc-11eb-93c9-65094f8574c1.png)

**Comment by pirquessa** [comment]
> Je pensais que c'était simple de modifier les fichiers d'une extension, donc j'ai bêtement récupérer le xpi dans le dossier des extensions, je l'ai renommé en zip, puis j'ai fait des modifs manuelles.

Il est ou ce dossier, je ne le vois pas dans C:\Users\USER\AppData\Local\Mozilla\Firefox\Profiles\ID.default

**Comment by dunglas** [comment]
Sinon il suffit de "cloner" ce dépôt et de choisir n'importe quel fichier à la racine du dossier via l'interface qu'a montré @Cuervino. C'est aussi possible d'utiliser l'outil [web-ext](https://extensionworkshop.com/documentation/develop/getting-started-with-web-ext/) de Mozilla qui est super pratique.

**Comment by Cuervino** [comment]
Les 3 minutes ont bien marché de notre côté, je pense que l'on peut clore l'issue ;-)
