### ISSUE TITLE
Comment peut-on savoir si l'extension fonctionne correctement ?

### ISSUE THREAD

**Issue by lmagendie** [dunglas/vaccin.click#13]
Bonjour, merci pour cette extension !
Après l'avoir l'installée, j'ai ajouté 7 centres avec l'option **Réserver automatiquement** (et je suis bien authentifié sur Doctolib).
Comment peut-on savoir si l'extension fonctionne correctement ? merci

**Comment by dunglas** [comment]
Bonjour,

La procédure de vérification est définie ici : https://github.com/dunglas/vaccin.click/issues/8#issuecomment-842985441
Plus d'infos dans cet échange sur Twitter : https://twitter.com/dunglas/status/1394663966299852804?s=20

**Comment by lmagendie** [comment]
Merci !

**Comment by julienw** [comment]
Depuis une modification du génial @pirquessa (présente dans la dernière version), l'activité est remontée directement dans l'interface de l'extension:
![image](https://user-images.githubusercontent.com/454175/119394735-d48b8700-bcd2-11eb-8798-4664412af347.png)

=> je ferme ce ticket, mais n'hésitez pas à remonter d'autres soucis!
