### ISSUE TITLE
onglet s'ouvre mais pas de réservation

### ISSUE THREAD

**Issue by florentlagoda** [dunglas/vaccin.click#16]
Tout d'abord très belle initiative !
Je ne sais pas si c'est suite à la mise à jour de l'extension de ce matin mais au moins 5 onglets se sont ouvert dans la matinée et pourtant aucun créneau n'etait disponible dans les 24h.
Ou alors je n'ai pas de chance le créneau a été pris dan les 5 minutes ?

**Comment by Deuchnord** [comment]
J'ai eu la même chose ce matin, je pense que c'est juste un manque de chance : la plupart du temps, je voyais un horaire disponible, mais le temps de réserver, il ne l'était plus.

**Comment by pirquessa** [comment]
Oui, l'extension, fais un pre check pour toi mais il faut quand meme être rapide pour réserver. Ca ne me semble pas être un bug.

**Comment by julienw** [comment]
Oui, la même chose se passe d'ailleurs même sur doctolib. On espère tous qu'il y ait assez de doses pour éviter ça :(

Je ferme ce ticket parce qu'on ne peut pas faire grand chose pour ça...

**Comment by pavan2202** [comment]
i didn't getting your language .can you please speak in english


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by pirquessa** [comment]
Do you have any issues @pavan2202?
