### ISSUE TITLE
L'extension semble ne pas marcher, plusieurs erreurs dans les logs

### ISSUE THREAD

**Issue by Nodjo** [dunglas/vaccin.click#19]
J'ai suivi le conseil indiqué ici (https://github.com/dunglas/vaccin.click/issues/8#issuecomment-842985441) pour vérifier si l'extension marchait, et la réponse est non. De plus j'ai plusieurs erreurs dans la console, cf cette screenshot:

![Capture d’écran de 2021-05-19 18-11-41](https://user-images.githubusercontent.com/3677487/118847215-cbaf4580-b8cd-11eb-810a-b533be094765.png)

**Comment by FlavienR** [comment]
J'ai également l'erreur Un en-tête X-Frame-Options non valide a été trouvé lors du chargement de « https://www.doctolib.fr/etc" :  "ALLOWALL" n'est pas une directive valide. Si je comprends bien ([ceci](https://stackoverflow.com/questions/27358966/how-to-set-x-frame-options-on-iframe) par exemple), ça veut dire que le problème vient de Doctolib ? Comment se fait-il que tout le monde n'ait pas le problème ?

**Comment by dunglas** [comment]
Les premières erreurs sont effectivement "normales" : la "closed conduit" est due à [un bug connu de Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1633315) qui ne porte pas à conséquence, et les erreurs liées à `x-frame-options` sont dues au code Doctolib sur lequel nous n'avons pas la main, mais n'empêchent pas non plus le fonctionnement de l'extension.

En revanche le fait qu'aucun log "aucun créneau" ne s'affiche n'est pas normal. Pouvez-vous m'envoyer les URL des centres que vous surveillez svp ?

> mais j'ai réussi à faire marcher l'extension en me connectant à Firefox

Étrange, ça devrait fonctionner même sans être connecté (mais je n'ai pas testé). D'après [la doc](https://wiki.mozilla.org/WebExtensions/chrome.storage.sync), si l'utilisateur n'est pas connecté, le stockage local est automatiquement utilisé en fallback (chez moi ça fonctionne).

**Comment by Nodjo** [comment]
Voici les deux centres que je suis:

https://www.doctolib.fr/vaccination-covid-19/issy-les-moulineaux/centre-de-vaccination-covid-issy-les-moulineaux?highlight%5Bspeciality_ids%5D%5B%5D=5494

https://www.doctolib.fr/vaccination-covid-19/paris/vaccinodrome-covid-19-porte-de-versailles?highlight%5Bspeciality_ids%5D%5B%5D=5494

J'ai regardé à nouveau et j'ai quelques nouvelles erreurs dans le log, je ne sais pas si elles sont pertinentes:

![Capture d’écran de 2021-05-19 23-47-10](https://user-images.githubusercontent.com/3677487/118888905-98d07600-b8fc-11eb-93f4-725c8204bb44.png)


Je suis sous Ubuntu 20.04 avec un Firefox à jour (88.0.1 (64 bits)), je ne suis pas "connecté à Firefox"

**Comment by cmpprevot** [comment]
même problème chez moi avec une erreur sur le "ALLOWALL". Voici mes log.

![image](https://user-images.githubusercontent.com/50751821/118965225-b9ceb080-b968-11eb-8e3b-1e147117497e.png)

Je suis pas très à l'aise en js mais je vais essayer de jeter un coup d'oeil de mon côté également

**Comment by julienw** [comment]
Pour ces 2 centres, j'ai aujourd'hui un "Réservation indisponible: Vous ne pouvez pas prendre rendez-vous en ligne avec ce praticien.". J'imagine que c'est lié ?

On _devrait_ quand même voir des objets d'erreur d'après mon expérience, donc c'est un peu curieux.

**Comment by FlavienR** [comment]
Dans mon cas, ça marche une fois sur deux environ je dirais. Pou un même centre je peux avoir ce log par exemple ("aucun créneau") :
![image](https://user-images.githubusercontent.com/5755585/119034954-51ef8880-b9af-11eb-9201-33ea3a50a1e5.png)
Puis un peu plus tard "document.getElementById(...) is null" dans book.js ligne 202 :
![image](https://user-images.githubusercontent.com/5755585/119037566-6ed98b00-b9b2-11eb-986b-05f5806a8b32.png)
Puis ça remarche et ainsi de suite.
Je suis sur la version 1.5 mais j'avais le problème avec la 1.2 aussi.
Exemple de centre : https://www.doctolib.fr/vaccination-covid-19/paris/centre-de-vaccination-covid-19-paris-8e?highlight%5Bspeciality_ids%5D%5B%5D=5494

**Comment by dunglas** [comment]
@julienw @Nodjo avec la dernière version, j'obtiens "Injection ARNm non disponible 2" pour ces deux centres, ce qui semble logique dans l'état actuel des réservations disponibles.

**Comment by Cameleon** [comment]
Bonjour, 
Je moi aussi plein d'erreurs dans les logs. Est-ce normal?

07:51:47,577
Object { type: "error", url: "https://www.doctolib.fr/centre-de-sante/joue-les-tours/centr…tion-joue-les-tours?highlight%5Bspeciality_ids%5D%5B%5D=5494", location: {…}, error: {…} }
index.js:45:13
07:54:50,834
Object { type: "error", url: "https://www.doctolib.fr/centre-de-sante/joue-les-tours/centr…tion-joue-les-tours?highlight%5Bspeciality_ids%5D%5B%5D=5494", location: {…}, error: {…} }
index.js:45:13
07:55:44,025 Unchecked lastError value: Error: undefined has no properties 219 preload.js:234
07:55:46,549 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    updatePopupStats moz-extension://b0db1438-2b36-43d4-a563-1a5fa9e714e5/lib/ui-service.js:231
ui-service.js:231:25
07:55:46,554 Unchecked lastError value: Error: undefined has no properties 40 preload.js:234
    tryLoadCssAndScripts moz-extension://b0db1438-2b36-43d4-a563-1a5fa9e714e5/lib/content-script/preload.js:234
07:55:47,515 Use of nsIFile in content process is deprecated. NetUtil.jsm:253:8
07:55:47,609 Unchecked lastError value: Error: undefined has no properties 213 preload.js:234
07:55:50,061 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    updatePopupStats moz-extension://b0db1438-2b36-43d4-a563-1a5fa9e714e5/lib/ui-service.js:231
ui-service.js:231:25
07:55:50,080 Unchecked lastError value: Error: undefined has no properties 397 preload.js:234
07:55:54,473 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    updatePopupStats moz-extension://b0db1438-2b36-43d4-a563-1a5fa9e714e5/lib/ui-service.js:231
ui-service.js:231:25
07:55:54,475 Unchecked lastError value: Error: undefined has no properties 199 preload.js:234
07:55:56,667 Unchecked lastError value: Error: sender.tab is undefined 666 preload.js:234
07:56:04,021 Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved
preload.js:234
07:56:04,023 Unchecked lastError value: Error: sender.tab is undefined 813 preload.js:234
07:56:12,995 sendRemoveListener on closed conduit extension@vaccin.click.274878216030 ConduitsChild.jsm:108
07:56:13,025 Unchecked lastError value: Error: sender.tab is undefined 574 preload.js:234
07:56:19,394 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    updatePopupStats moz-extension://b0db1438-2b36-43d4-a563-1a5fa9e714e5/lib/ui-service.js:231
ui-service.js:231:25
07:56:19,394 Unchecked lastError value: Error: sender.tab is undefined 448 preload.js:234
07:56:24,392 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    updatePopupStats moz-extension://b0db1438-2b36-43d4-a563-1a5fa9e714e5/lib/ui-service.js:231
ui-service.js:231:25
07:56:24,392 Unchecked lastError value: Error: sender.tab is undefined 1132 preload.js:234
07:56:37,085 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    updatePopupStats moz-extension://b0db1438-2b36-43d4-a563-1a5fa9e714e5/lib/ui-service.js:231
ui-service.js:231:25
07:56:37,096 Unchecked lastError value: Error: sender.tab is undefined 570 preload.js:234
07:56:43,408 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    updatePopupStats moz-extension://b0db1438-2b36-43d4-a563-1a5fa9e714e5/lib/ui-service.js:231
ui-service.js:231:25
07:56:43,409 Unchecked lastError value: Error: sender.tab is undefined 126 preload.js:234
07:56:44,754 Unchecked lastError value: Error: undefined has no properties 503 preload.js:234
07:56:50,307 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    updatePopupStats moz-extension://b0db1438-2b36-43d4-a563-1a5fa9e714e5/lib/ui-service.js:231
ui-service.js:231:25
07:56:50,307 Unchecked lastError value: Error: undefined has no properties 356 preload.js:234
07:56:54,445 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    updatePopupStats moz-extension://b0db1438-2b36-43d4-a563-1a5fa9e714e5/lib/ui-service.js:231
ui-service.js:231:25
07:56:54,451 Unchecked lastError value: Error: undefined has no properties 359 preload.js:234
07:56:58,594 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    updatePopupStats moz-extension://b0db1438-2b36-43d4-a563-1a5fa9e714e5/lib/ui-service.js:231
ui-service.js:231:25
07:56:58,604 Unchecked lastError value: Error: undefined has no properties 262 preload.js:234
07:57:03,635 Use of nsIFile in content process is deprecated. 24 NetUtil.jsm:253:8
07:57:03,709 NS_BASE_STREAM_CLOSED: Component returned failure code: 0x80470002 (NS_BASE_STREAM_CLOSED) [nsIInputStream.available] DevToolsUtils.js:567
07:57:03,714 Unchecked lastError value: Error: undefined has no properties 1398 preload.js:234
07:57:19,368 Unchecked lastError value: Error: sender.tab is undefined 2172 preload.js:234
07:57:49,624 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    updatePopupStats moz-extension://b0db1438-2b36-43d4-a563-1a5fa9e714e5/lib/ui-service.js:231
ui-service.js:231:25
07:57:49,670 Unchecked lastError value: Error: sender.tab is undefined 100 preload.js:234
07:57:50,898 Unchecked lastError value: Error: sender.tab is undefined 20 preload.js:234
07:57:51,081 sendRemoveListener on closed conduit extension@vaccin.click.274878215623 ConduitsChild.jsm:108
07:57:51,143 Un en-tête X-Frame-Options non valide a été trouvé lors du chargement de « https://www.doctolib.fr/centre-de-sante/joue-les-tours/centre-de-vaccination-joue-les-tours?highlight%5Bspeciality_ids%5D%5B%5D=5494 » : « ALLOWALL » n’est pas une directive valide. centre-de-vaccination-joue-les-tours
07:57:51,197 Unchecked lastError value: Error: sender.tab is undefined 9 preload.js:234
07:57:51,305 Unchecked lastError value: Error: sender.tab is undefined 27 preload.js:234
07:57:52,025 Certains cookies utilisent incorrectement l’attribut recommandé « SameSite » 2
07:57:52,454 Unchecked lastError value: Error: sender.tab is undefined preload.js:234
07:57:52,454 Unchecked lastError value: Error: sender.tab is undefined preload.js:234
07:57:52,455 Unchecked lastError value: Error: sender.tab is undefined preload.js:234
07:57:52,455 Unchecked lastError value: Error: sender.tab is undefined preload.js:234
07:57:52,455 Unchecked lastError value: Error: sender.tab is undefined preload.js:234
07:57:52,455 Unchecked lastError value: Error: sender.tab is undefined preload.js:234
07:57:53,101 Unchecked lastError value: Error: sender.tab is undefined 18 preload.js:234
07:57:53,411 Unchecked lastError value: Error: sender.tab is undefined 9 preload.js:234
07:57:53,546 Unchecked lastError value: Error: sender.tab is undefined 18 preload.js:234
07:57:53,981 Unchecked lastError value: Error: sender.tab is undefined 9 preload.js:234
07:57:54,095 Unchecked lastError value: Error: sender.tab is undefined 9 preload.js:234
07:57:54,202 Unchecked lastError value: Error: sender.tab is undefined 37 preload.js:234
07:57:54,827
Object { type: "error", url: "https://www.doctolib.fr/centre-de-sante/joue-les-tours/centr…tion-joue-les-tours?highlight%5Bspeciality_ids%5D%5B%5D=5494", location: {…}, error: {…} }
index.js:45:13
07:57:54,850 Unchecked lastError value: Error: sender.tab is undefined 3 preload.js:234
07:57:54,855 Unchecked lastError value: Error: sender.tab is undefined 7 preload.js:234
07:57:54,992 Unchecked lastError value: Error: sender.tab is undefined 10 preload.js:234
07:57:55,107 Unchecked lastError value: Error: sender.tab is undefined 20 preload.js:234

**Comment by dunglas** [comment]
@Cameleon est-ce que tu pourrais déplier la clef "error" stp pour voir le message ? Si c'est "créneau non disponible" alors c'est normal (il faut juste attendre que le centre ajoute des RDV). Sinon c'est sûrement un bug.

**Comment by Nodjo** [comment]
En effet, j'ai maintenant "Aucun créneau disponible" pour un centre et "Injection ARNm non disponible" pour l'autre.

Merci !

**Comment by Cameleon** [comment]
> @Cameleon est-ce que tu pourrais déplier la clef "error" stp pour voir le message ? Si c'est "créneau non disponible" alors c'est normal (il faut juste attendre que le centre ajoute des RDV). Sinon c'est sûrement un bug.

Oui c'est bien "aucun creneau dispo" donc c'est normal. Peut-être serait-il possible que l'extension informe l'utilisateur qu'elle a recherché des créneaux mais qu'ils ne sont pas dispo? Ca permettrait d'être rassuré sur son bon fonctionnement.

**Comment by pirquessa** [comment]
C'est justement l'objet de ma PR https://github.com/dunglas/vaccin.click/pull/41 :)

**Comment by dunglas** [comment]
Utilisez-vous l'extension "Privacy Badger" ? L'erreur `sender.tab is undefined` semble levée par cette extension, mais n'empêche pas vaccin.click de fonctionner.

**Comment by fawa123** [comment]
Bonjour 
Pour ma part pas de message "aucun créneau disponible" et des messages d'erreur  : 

Object { type: "error", url: "https://www.doctolib.fr/vaccination-covid-19/clisson/centre-…sson-gorges-getigne?highlight%5Bspeciality_ids%5D%5B%5D=5494", location: {…}, error: {…} }
index.js:45:13
sendRemoveListener on closed conduit extension@vaccin.click.137438954496 ConduitsChild.jsm:108
    _send resource://gre/modules/ConduitsChild.jsm:108
    _send self-hosted:1277
    removeListener resource://gre/modules/ExtensionChild.jsm:663
    removeListener resource://gre/modules/ExtensionChild.jsm:886
    onChanged chrome://extensions/content/child/ext-storage.js:332
    removeListener resource://gre/modules/ExtensionCommon.jsm:2523
    revoke resource://gre/modules/ExtensionCommon.jsm:2545
    close resource://gre/modules/ExtensionCommon.jsm:2550
    unload resource://gre/modules/ExtensionCommon.jsm:912
    close resource://gre/modules/ExtensionContent.jsm:930
    destroyed resource://gre/modules/ExtensionContent.jsm:1008
    observe resource://gre/modules/ExtensionContent.jsm:1026
Object { type: "error", url: "https://www.doctolib.fr/vaccination-covid-19/montaigu-vendee…-terres-de-montaigu?highlight%5Bspeciality_ids%5D%5B%5D=5494", location: {…}, error: {…} }
index.js:45:13
sendRemoveListener on closed conduit extension@vaccin.click.137438954501 ConduitsChild.jsm:108
Un en-tête X-Frame-Options non valide a été trouvé lors du chargement de « https://www.doctolib.fr/vaccination-covid-19/vallet/centre-de-vaccination-covid-sud-loire-vignoble-site-de-vallet?highlight%5Bspeciality_ids%5D%5B%5D=5494 » : « ALLOWALL » n’est pas une directive valide.
centre-de-vaccination-covid-sud-loire-vignoble-site-de-vallet
Certains cookies utilisent incorrectement l’attribut recommandé « SameSite » 2
Object { type: "error", url: "https://www.doctolib.fr/vaccination-covid-19/vallet/centre-d…oble-site-de-vallet?highlight%5Bspeciality_ids%5D%5B%5D=5494", location: {…}, error: {…} }
index.js:45:13
sendRemoveListener on closed conduit extension@vaccin.click.137438954511 ConduitsChild.jsm:108
Object { type: "error", url: "https://www.doctolib.fr/vaccination-covid-19/montaigu-vendee…-terres-de-montaigu?highlight%5Bspeciality_ids%5D%5B%5D=5494", location: {…}, error: {…} }
index.js:45:13
Cette page utilise la propriété non standard « zoom ». Envisagez d’utiliser calc() dans les valeurs des propriétés pertinentes ou utilisez « transform » avec « transform-origin: 0 0 ». util.js:23:392
sendRemoveListener on closed conduit extension@vaccin.click.137438954521 ConduitsChild.jsm:108
Object { type: "error", url: "https://www.doctolib.fr/vaccination-covid-19/montaigu-vendee…-terres-de-montaigu?highlight%5Bspeciality_ids%5D%5B%5D=5494", location: {…}, error: {…} }
index.js:45:13
sendRemoveListener on closed conduit extension@vaccin.click.137438954530 ConduitsChild.jsm:108
Object { type: "error", url: "https://www.doctolib.fr/vaccination-covid-19/montaigu-vendee…-terres-de-montaigu?highlight%5Bspeciality_ids%5D%5B%5D=5494", location: {…}, error: {…} }
index.js:45:13
sendRemoveListener on closed conduit extension@vaccin.click.137438954535 ConduitsChild.jsm:108
Object { type: "error", url: "https://www.doctolib.fr/vaccination-covid-19/montaigu-vendee…-terres-de-montaigu?highlight%5Bspeciality_ids%5D%5B%5D=5494", location: {…}, error: {…} }
index.js:45:13
sendRemoveListener on closed conduit extension@vaccin.click.137438954540 ConduitsChild.jsm:108
Object { type: "error", url: "https://www.doctolib.fr/vaccination-covid-19/montaigu-vendee…-terres-de-montaigu?highlight%5Bspeciality_ids%5D%5B%5D=5494", location: {…}, error: {…} }
index.js:45:13
sendRemoveListener on closed conduit extension@vaccin.click.137438954545 ConduitsChild.jsm:108
Object { type: "error", url: "https://www.doctolib.fr/vaccination-covid-19/montaigu-vendee…-terres-de-montaigu?highlight%5Bspeciality_ids%5D%5B%5D=5494", location: {…}, error: {…} }
index.js:45:13
sendRemoveListener on closed conduit extension@vaccin.click.137438954550 ConduitsChild.jsm:108
Object { type: "error", url: "https://www.doctolib.fr/vaccination-covid-19/montaigu-vendee…-terres-de-montaigu?highlight%5Bspeciality_ids%5D%5B%5D=5494", location: {…}, error: {…} }
index.js:45:13
sendRemoveListener on closed conduit extension@vaccin.click.137438954555 ConduitsChild.jsm:108
Object { type: "error", url: "https://www.doctolib.fr/vaccination-covid-19/montaigu-vendee…-terres-de-montaigu?highlight%5Bspeciality_ids%5D%5B%5D=5494", location: {…}, error: {…} }
index.js:45:13
sendRemoveListener on closed conduit extension@vaccin.click.137438954560 ConduitsChild.jsm:108
Object { type: "error", url: "https://www.doctolib.fr/vaccination-covid-19/montaigu-vendee…-terres-de-montaigu?highlight%5Bspeciality_ids%5D%5B%5D=5494", location: {…}, error: {…} }
index.js:45:13

Que puis-je faire? 
Merci

**Comment by dunglas** [comment]
Pouvez-vous déplier la clef "error" svp ? C'est la qu'il sera indiqué l'erreur exacte (y compris si c'est "aucun créneau disponible").

**Comment by fawa123** [comment]
Je ne sais pas ce qu'est "clé "error" , peut être ca : 

Object { type: "error", url: "https://www.doctolib.fr/vaccination-covid-19/clisson/centre-…sson-gorges-getigne?highlight%5Bspeciality_ids%5D%5B%5D=5494", location: {…}, error: {…} }
index.js:45:13
Object { type: "error", url: "https://www.doctolib.fr/vaccination-covid-19/montaigu-vendee…-terres-de-montaigu?highlight%5Bspeciality_ids%5D%5B%5D=5494", location: {…}, error: {…} }
index.js:45:13
Object { type: "error", url: "https://www.doctolib.fr/vaccination-covid-19/vallet/centre-d…oble-site-de-vallet?highlight%5Bspeciality_ids%5D%5B%5D=5494", location: {…}, error: {…} }
index.js:45:13
Object { type: "error", url: "https://www.doctolib.fr/vaccination-covid-19/clisson/centre-…sson-gorges-getigne?highlight%5Bspeciality_ids%5D%5B%5D=5494", location: {…}, error: {…} }
index.js:45:13
Object { type: "error", url: "https://www.doctolib.fr/vaccination-covid-19/vertou/centre-d…19-mairie-de-vertou?highlight%5Bspeciality_ids%5D%5B%5D=5494", location: {…}, error: {…} }
index.js:45:13
Object { type: "error", url: "https://www.doctolib.fr/vaccination-covid-19/montaigu-vendee…-terres-de-montaigu?highlight%5Bspeciality_ids%5D%5B%5D=5494", location: {…}, error: {…} }
index.js:45:13
Object { type: "error", url: "https://www.doctolib.fr/vaccination-covid-19/vallet/centre-d…oble-site-de-vallet?highlight%5Bspeciality_ids%5D%5B%5D=5494", location: {…}, error: {…} }
index.js:45:13
Object { type: "error", url: "https://www.doctolib.fr/vaccination-covid-19/clisson/centre-…sson-gorges-getigne?highlight%5Bspeciality_ids%5D%5B%5D=5494", location: {…}, error: {…} }
index.js:45:13
Object { type: "error", url: "https://www.doctolib.fr/vaccination-covid-19/vertou/centre-d…19-mairie-de-vertou?highlight%5Bspeciality_ids%5D%5B%5D=5494", location: {…}, error: {…} }
index.js:45:13
Object { type: "error", url: "https://www.doctolib.fr/vaccination-covid-19/montaigu-vendee…-terres-de-montaigu?highlight%5Bspeciality_ids%5D%5B%5D=5494", location: {…}, error: {…} }
index.js:45:13

**Comment by dunglas** [comment]
Si si elle apparaît dans tous les copiés collés. Il faudrait juste la déplier. La petite flèche après "error:".

**Comment by fawa123** [comment]
Peut être cela : 

Object { type: "error", url: "https://www.doctolib.fr/vaccination-covid-19/vallet/centre-d…oble-site-de-vallet?highlight%5Bspeciality_ids%5D%5B%5D=5494", location: {…}, error: {…} }
​
error: Object { name: "Error", message: "Aucun créneau disponible 1", stack: "checkAvailability@moz-extension://f7460633-9d7a-5045-bc09-295e2d26b9ee/content_scripts/doctolib/book.js:258:29\n" }
​
location: Object { name: "Centre de Vaccination Covid-19 Sud Loire Vignoble - Site de Vallet", img: "https://res.cloudinary.com/doctolib/image/upload/q_auto:eco,…to,w_160,h_160,c_fill,g_face/default_organization_avatar.jpg" }
​
type: "error"
​
url: "https://www.doctolib.fr/vaccination-covid-19/vallet/centre-d…oble-site-de-vallet?highlight%5Bspeciality_ids%5D%5B%5D=5494"
​
<prototype>: Object { … }

**Comment by dunglas** [comment]
Oui, donc c'est bien le comportent attendu. Il faut juste attendre que votre centre ajoute des créneaux.

**Comment by fawa123** [comment]
super merci beaucoup ! 
Je vous souhaite une belle journée.
