### ISSUE TITLE
Problème sur les centres avec la question "avez vous déjà consulté un praticien de cet établissement"

### ISSUE THREAD

**Issue by julienw** [dunglas/vaccin.click#20]
Sur des centres tels que: https://www.doctolib.fr/vaccination-covid-19/paris/centre-de-vaccination-covid-paris-15e?highlight%5Bspeciality_ids%5D%5B%5D=5494
avec cette boite:
![image](https://user-images.githubusercontent.com/454175/118929127-68acc580-b944-11eb-828b-8b1186f7b821.png)

j'ai l'impression que l'extension n'arrive pas à passer cette étape pour réaliser la réservation.

J'obtiens une erreur qui est (je la fais de tête, possiblement pas 100% exacte) `can't access textContent, document.getElementByid('...') is null/undefined`.

**Comment by julienw** [comment]
Erreur similaire avec cette boite:
![image](https://user-images.githubusercontent.com/454175/118929794-436c8700-b945-11eb-86a5-34531dd0ef51.png)
Dans ce cas c'est moins grave évidemment.

**Comment by julienw** [comment]
J'ai aussi des centres avec cette question:
![image](https://user-images.githubusercontent.com/454175/118930485-153b7700-b946-11eb-827e-0abee21796d2.png)

**Comment by julienw** [comment]
Celui-ci également: https://www.doctolib.fr/vaccination-covid-19/paris/centre-de-vaccination-mairie-du-7eme-paris?highlight%5Bspeciality_ids%5D%5B%5D=5494
ne semble pas correspondre à la regexp utilisée:
![image](https://user-images.githubusercontent.com/454175/118930618-4320bb80-b946-11eb-8ba1-558a65fb6b12.png)

**Comment by julienw** [comment]
J'ai presque résolu le premier cas (j'ai résolu les suivants) mais j'ai une contrainte... je finirai après le déjeuner probablement. Stay tuned!

**Comment by dunglas** [comment]
Super, merci beaucoup pour ce gros boulot. N'hésitez pas à ouvrir la PR en brouillon que je puisse jeter un œil. Tous les cas me semblent légitimes, il n'y a que ce cas ou l'erreur était "volontaire" (par flemme il faut l'avouer ^^) : 
![image](https://user-images.githubusercontent.com/57224/118941813-6a7d8580-b952-11eb-97c9-59adc7060a06.png)

**Comment by dunglas** [comment]
J'ai poussé le support de celui-ci dans #24

![image](https://user-images.githubusercontent.com/57224/118950240-4d4cb500-b95a-11eb-99cf-ab8a1459d5e0.png)

**Comment by amaixent** [comment]
Hello !
Déjà, MERCI pour ce travail ça me redonne espoir d'avoir un rdv rapidement :sob: 
Moi j'ai un souci avec ce type de centre : https://www.doctolib.fr/vaccination-covid-19/paris/centre-de-vaccination-covid-19-ville-de-paris?highlight%5Bspeciality_ids%5D%5B%5D=5494&pid=practice-164926
J'ai bien autorisé l'extension à réserver pour moi, mais quand j'arrive sur l'onglet j'ai ça :
![Screenshot from 2021-05-20 11-38-55](https://user-images.githubusercontent.com/11490959/118956701-21343280-b960-11eb-9978-9a207e50c5f5.png)
Rien n'a été sélectionné (dans le select on a le choix entre pfizer ou moderna), aucun rdv n'a été pris :thinking:

**Comment by julienw** [comment]
> J'ai poussé le support de celui-ci dans #24
> 
> ![image](https://user-images.githubusercontent.com/57224/118950240-4d4cb500-b95a-11eb-99cf-ab8a1459d5e0.png)

j'avais un truc qui ressemblait ;) bon je vais rebaser du coup !

**Comment by julienw** [comment]
> Hello !
> Déjà, MERCI pour ce travail ça me redonne espoir d'avoir un rdv rapidement sob
> Moi j'ai un souci avec ce type de centre : https://www.doctolib.fr/vaccination-covid-19/paris/centre-de-vaccination-covid-19-ville-de-paris?highlight%5Bspeciality_ids%5D%5B%5D=5494&pid=practice-164926
> J'ai bien autorisé l'extension à réserver pour moi, mais quand j'arrive sur l'onglet j'ai ça :
> ![Screenshot from 2021-05-20 11-38-55](https://user-images.githubusercontent.com/11490959/118956701-21343280-b960-11eb-9978-9a207e50c5f5.png)
> Rien n'a été sélectionné (dans le select on a le choix entre pfizer ou moderna), aucun rdv n'a été pris thinking

Je crois que des fois, ce qui arrive, c'est que l'extension détecte un rendez-vous en arrière-plan, mais que le temps d'ouvrir l'onglet et de le booker c'est trop tard... Il faut s'armer de patience !

**Comment by amaixent** [comment]
Aha j'espérais que ce n'était pas ça le problème, mais concernant les centres sur Paris ça ne m'étonne pas :grimacing: merci pour ta réponse :blush:

**Comment by julienw** [comment]
Pour info, j'ai pushé mes changements sur #25. J'ai revu le code fait dans #24 à partir de ce que j'avais fait auparavant, mais je peux enlever des bouts si c'est préférable.

**Comment by julienw** [comment]
Nouveau type qui ne fonctionne pas: centres SOS Médecin avec une partie "spécialité": https://www.doctolib.fr/centre-de-sante/paris/sos-medecins-paris?pid=practice-165129
(on verra dans une autre PR)
