### ISSUE TITLE
Make the image clickable

### ISSUE THREAD

**Issue by alexislefebvre** [dunglas/vaccin.click#26]
Hello,
please add a link on the image on https://vaccin.click/ It would make it easier to read.

**Comment by dunglas** [comment]
Fait !

**Comment by alexislefebvre** [comment]
@dunglas merci ! C'est déployé ? L'image n'a pas de lien.

**Comment by dunglas** [comment]
Ah je crois qu'on ne parlait pas de la même image !

**Comment by alexislefebvre** [comment]
Ah, je parlais de cette capture d'écran 😃 :

> ![image](https://user-images.githubusercontent.com/2071331/119236162-395daa80-bb36-11eb-9ef9-eef84b192109.png)
