### ISSUE TITLE
Doctolib se protège avec une file d'attente...

### ISSUE THREAD

**Issue by pirquessa** [dunglas/vaccin.click#27]
Depuis hier, rien ne se passait avec l'extension... En regardant maintenant, je vois que Doctolib se protège contre notre spam...

![Capture](https://user-images.githubusercontent.com/13021033/118991889-6bc7a600-b984-11eb-8966-34e2ea8024de.JPG)

Il faut vraiment limiter le nombre de calls en parallèle j'ai l'impression :(

**Comment by dunglas** [comment]
Ah j'ai eu ça une fois aussi au moment du développement, mais je n'ai jamais réussi à reproduire. J'ai l'impression que ça fait ça que lorsque les serveurs  de Doctolib sont chargés. Si quelqu'un a nouveau cette page pourriez-vous faire une copie du HTML généré histoire que l'on arrête la vérification quand ça arrive afin de soulager leurs serveurs ?

**Comment by floriangagnard** [comment]
J'ai vu cette page le jour de l'ouverture de la vaccination à tous pour les créneaux vides. Depuis, plus rien. Je n'aurais donc pas tendance à dire que c'est lié à ton addon car plutôt lié aux évènements ?
Cela dit, je suis loggé sur doctolib depuis. Etais-tu loggé sur doctolib @pirquessa ?

**Comment by pirquessa** [comment]
Je clos, je reproduis plus
