### ISSUE TITLE
Page blanche quand on essaie de trouver un centre

### ISSUE THREAD

**Issue by jdeniau** [dunglas/vaccin.click#36]
Bonjour,

Je viens d'installer l'extension, mais quand je clique sur "trouver un centre", j'obtiens une page blanche.

On voit derrière la console de l'extension.

![image](https://user-images.githubusercontent.com/1398469/119029402-ddb1e680-b9a8-11eb-88b9-c72a7399cde1.png)

**Comment by jdeniau** [comment]
OK je viens de régler le problème en inspectant le code et en allant directement sur https://www.doctolib.fr/vaccination-covid-19 et j'ai vu le nouveau bouton "Ajouter un centre".

**Comment by dunglas** [comment]
Très étrange, je n'arrive pas à reproduire le problème de mon côté (ça ouvre bien un nouvel onglet).

**Comment by jdeniau** [comment]
Je n'ai pas eu le temps de regarder en détail pourquoi ça ne fonctionne pas, mais en tout cas j'ai bien eu la notification et j'ai pu réserver un créneau pour demain ! 

Pour info dans la fenêtre de l'extension, on peut bien faire "clic droit > ouvrir dans un nouvel onglet" et ça fonctionne parfaitement.

Bien joué pour l'extension 👏 💯

**Comment by pirquessa** [comment]
Merci !
