### ISSUE TITLE
Imposible d'ajouter a Firefox

### ISSUE THREAD

**Issue by gege3232** [dunglas/vaccin.click#39]
L'extension ne peut pas être ajoutée à Forefox. Le bouton "Ajouter à Firefox" n'est pas activé. J'utilise Firefox 88.1.4. Merci d'avance pour votre support

**Comment by julienw** [comment]
Bonjour @gege3232, pouvez-vous vérifier la version de Firefox que vous utilisez ? En effet la version 88.1.4 n'existe pas à ma connaissance. Vous pouvez avoir cette info en allant à l'adresse `about:support`.

Sur quel système essayez-vous d'installer l'extension ? Elle ne fonctionne que sur Firefox version "desktop" (c'est-à-dire sur ordinateur).

Merci pour votre retour

**Comment by gege3232** [comment]
Bonjour,

Merci de m'avoir contacté. En effet j'essayais de l'installer sur mon téléphone portable. Je comprends maintenant que ce n'est pas possible. Sur mon PC je peux l'installer sans souci.  Merci!

Get Outlook para Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by dunglas** [comment]
Merci pour ton retour @gege3232 ! J'ai mis à jour le site pour indiquer clairement que ça ne fonctionne que sur ordinateur. J'espère que ça évitera cette incompréhension aux futurs utilisateurs.
