### ISSUE TITLE
Nouvel onglet n'apparrait pas

### ISSUE THREAD

**Issue by LaurentNiasme** [dunglas/vaccin.click#40]
Bonjour
Tout d'abord, bravo pour l'initiative et ce bel outil.

Je l'ai bien utilisé sur mon compte et ça a bien marché. 
Je voulais renouveler l'expérience pour ma compagne, donc je me connecte sur son compte, sélectionne les centre de vaccination et plus rien ne se passe.

J'ai donc effacé toutes les données du modules puis de nouveau sélectionné les centre et rien ne se passe toujours. Testé sur 3 pc différents.

Je suis retourné sur mon compte et toujours pareil, plus rien ne bouge, pas de nouvel onglet.

Je me suis dit, le site doctolib a trouvé un moyen pour bloquer.

Pour le moment je retourne à la bonne vieille méthode, clic manuel :)

**Comment by julienw** [comment]
Que vois-tu quand tu vas avec l'adresse about:devtools-toolbox?id=extension%40vaccin.click&type=extension, puis dans l'onglet console ?
Si ça fonctionne, tu devrais voir des lignes du type `Object { type: "error", url: "https://www.doctolib.fr/vaccination-covid-19/paris/centre-de…highlight%5Bspeciality_ids%5D%5B%5D=5494&pid=practice-175177", location: {…}, error: {…} }` (au milieu d'autres erreurs qui ne sont pas problématiques généralement... mais tu peux toujours envoyer une copie d'écran en cas de doute)

**Comment by LaurentNiasme** [comment]
J'ai bien un objet d erreur par centre de vaccination sélectionné, mais plus bas j'ai un :
Promise rejected after context unloaded: page is undefined                                                 include.preload.js:1854
sendRemoveListener on closed conduit extension@vaccin.click.274877927687                   ConduitsChild.jsm:108


Là je suis en train de comprendre qu'il n'écoute plus evt des requêtes. (je dis ça alors que je n'ai pas lu tout ton code :D)

**Comment by dunglas** [comment]
Ces erreurs ne sont pas critiques et ne devraient pas empêcher le fonctionnement de l'extension.

**Comment by LaurentNiasme** [comment]
Petit screen
![image](https://user-images.githubusercontent.com/17691684/119156247-56ba4800-ba54-11eb-85f6-f8b792979570.png)

**Comment by pirquessa** [comment]
Il manque la partie de droite qui indique quel fichier à causer l'erreur... Ca aiderait ;)

**Comment by LaurentNiasme** [comment]
autant pour moi
![image](https://user-images.githubusercontent.com/17691684/119157128-26bf7480-ba55-11eb-8327-01def10e3471.png)

**Comment by LaurentNiasme** [comment]
Tout remarche bien :)

**Comment by pirquessa** [comment]
Super, je ferme donc :)
