### ISSUE TITLE
"aucun créneau disponible" n'apparait pas

### ISSUE THREAD

**Issue by charlesmaguin** [dunglas/vaccin.click#42]
[console vaccin click.txt](https://github.com/dunglas/vaccin.click/files/6524683/console.vaccin.click.txt)

Bonjour,

Désolé si je m'y prends mal pour signaler un pb, je débute.
J'ai regardé dans la console pour voir s'il y avait des "aucun créneau disponible", mais je n'en ai vu aucun.
Parmi tous les messages d'erreur, je n'ai pas su lequel vous copier alors j'ai copié l'ensemble de la console dans un bloc note, ci joint.

Merci pour cette extension malgré tout, lorsqu'elle fonctionne ça doit être super :)

**Comment by Nykola21402041** [comment]
Hello, as tu déplié le log pour voir l'ensemble comme ceci : 
![image](https://user-images.githubusercontent.com/46490980/119192903-1c1ad480-ba81-11eb-80e2-e8286c74d2ab.png)

**Comment by charlesmaguin** [comment]
Ah oui en effet, en dépliant on voit des "aucun créneau disponible 1"... désolé pour le dérangement, j'imagine que tout fonctionne alors.
