### ISSUE TITLE
Ne fonctionne pas, le message indiquant “aucun créneau disponible" n'apparait pas

### ISSUE THREAD

**Issue by didier92400** [dunglas/vaccin.click#43]

**Comment by dunglas** [comment]
Bonjour, est-ce qu'un autre message apparaît dans la console ? Quelle est l'URL du ou des centres que vous surveillez ?

**Comment by didier92400** [comment]
Bonjour, je voulais mettre une impression écran, mais je n'y arrive pas. Quelle est la méthode? J'ai une dizaine de centre en surveillance. dont le vaccinodrome de paris 15, et celui de l'arena Nanterre. J'ai supprimé firefox et effacé toute donnée... Merci, je deviens fou

**Comment by MaxOla** [comment]
Bonjour idem chez moi même après avoir désinstallé et réinstallé l'extension...
J'ai ça en console : 
![Toolbox - Extension  vaccin click 2021-05-22 09-27-29](https://user-images.githubusercontent.com/79079785/119218327-08eb2180-bae0-11eb-9aac-ce69ea3c8eb2.png)

**Comment by MaxOla** [comment]
Bonjour,

De mon côté j'ai l'impression également que l'extension n'arrive plus à réserver les créneaux, j'ai ça en console : 

![Toolbox - Extension  vaccin click 2021-05-22 09-29-33](https://user-images.githubusercontent.com/79079785/119218442-99c1fd00-bae0-11eb-9a47-bf8466350f81.png)

**Comment by pirquessa** [comment]
Vous pouvez essayer le code de la PR#12, il y a un retour utilisateur plus évident qu'actuellement

**Comment by julienw** [comment]
Le code de la #41 est maintenant disponible dans la dernière version de l'extension. @didier92400 tu dois pouvoir avoir plus d'informations depuis la fenêtre de l'extension. Qu'y vois-tu ?

**Comment by didier92400** [comment]
Oui c'est bon. Mais toujours pas de rendez vous sur Paris et ouest Parisien, en laissant le PC allumé 12h par jour. J espère que l extension sera à jour le 31 mai pour trouver un créneau pour les + 18 ans sans morbidité et sans être limité à j+1. Merci

**Comment by pirquessa** [comment]
Etonnant, j'ai trouvé pas mal de créneau aujourd'hui moi dans le sud Parisien... Tu as mis beaucoup de centres en surveillance ? Est-ce que tu as vérifié qu'ils proposent du Pfizer/Moderna ?

**Comment by didier92400** [comment]
Pourtant je vérifie sur le site de l'ARS et vite ma dose. Il y a un créneau tous les 3 heures en moyenne, et c est déjà pris lorsque l extension me le trouve. De toute façon, ce week end, il y avait très peu de centres ouverts, je crois que je vais attendre le 31.

**Comment by julienw** [comment]
Avec vite ma dose également, quand il trouve une dose, le temps de cliquer c'est souvent déjà trop tard... :/

Je pense qu'on peut fermer ce ticket, mais n'hésitez pas à remonter d'autres soucis rencontrés !
