### ISSUE TITLE
Créneau de schrodinger

### ISSUE THREAD

**Issue by pirquessa** [dunglas/vaccin.click#47]
Salut,

Voici un log bien étrange, on trouve un créneau ET il n'y a pas de créneau:

![image](https://user-images.githubusercontent.com/13021033/119272655-544c1f80-bc07-11eb-9e17-2e724c3e4aa7.png)

![image](https://user-images.githubusercontent.com/13021033/119272719-9ecd9c00-bc07-11eb-9900-8d865a8b4401.png)

https://www.doctolib.fr/vaccination-covid-19/palaiseau/centre-de-vaccination-covid-19-de-palaiseau-complexe-sportif-j-allain?highlight%5Bspeciality_ids%5D%5B%5D=5494

**Comment by dunglas** [comment]
Ça arrive parfois quand le créneau part très vite, typiquement entre le moment où la vérification automatique a lieu et le moment ou l'onglet s'ouvre.

**Comment by pirquessa** [comment]
Ha, pas bête ! Je me demandais comment j'allais pouvoir débuguer ca :p
