### ISSUE TITLE
vaccin.click ne fait pas la différence entre les rdv pour première et deuxième dose

### ISSUE THREAD

**Issue by treisska** [dunglas/vaccin.click#53]
Certains centres ont des créneaux différents pour la première et la deuxième dose.
vaccin.click ne fait pas la différence et annonce des créneaux disponibles dès qu'un créneau (1ere ou 2eme dose) est dispo.

Exemple : https://www.doctolib.fr/vaccination-covid-19/nanterre/centre-de-vaccination-covid-pld-arena?highlight%5Bspeciality_ids%5D%5B%5D=5494

**Comment by julienw** [comment]
Bonjour!

L'extension ne recherche que des premières doses et ignore les secondes doses. Mais il est possible qu'entre le temps où l'extension trouve une dose et où le tab s'ouvre ce créneau soit parti...

Je viens de vérifier spécifiquement ce centre, et ça fonctionne comme prévu (il y a des créneaux 2nde dose disponibles mais pas de 1ere dose, et l'extension échoue à trouver un créneau comme prévu).

Avez-vous vu cela souvent, et sur d'autres centres ?
Merci!

**Comment by treisska** [comment]
Bonjour,

Non je n'ai vu que sur ce centre en particulier, mais constamment pendant plusieurs heures.
Je vais relancer ma quête d'une dose, je rouvrirais le ticket si cela se reproduit.

Merci de la réponse rapide 🙂
