### ISSUE TITLE
Motif non trouvé pour le centre de nogent sur marne

### ISSUE THREAD

**Issue by julienw** [dunglas/vaccin.click#61]
Centre: https://www.doctolib.fr/centre-de-sante/nogent-sur-marne/accueil-ambulatoire-de-recours-ville-de-nogent-sur-marne-adp94?highlight%5Bspeciality_ids%5D%5B%5D=5494

Erreur:
17:15:30 - Centre de vaccination et dépistage Covid-19 - Nogent et le Perreux sur Marne - Echec - Catégorie de motif non trouvé. Motifs disponibles : Choisissez une catégorie, Patient de plus de 18 ans, Patient de 16 ans à 18 ans de très haute priorité (cf. liste HAS) ou proche de personnes immunodéprimées

(pas le temps de traiter maintenant, mais je traque)

**Comment by dunglas** [comment]
Je crois qu'on ne gère pas encore cette étape "spécialité".

**Comment by julienw** [comment]
Si si, ça fait partie des trucs que j'avais ajoutés pour SOS médecins
