### ISSUE TITLE
Message d'erreur: "Impossible de cliquer sur le slot"

### ISSUE THREAD

**Issue by kabarigou** [dunglas/vaccin.click#71]
Bonjour,

J'essaie d'utiliser votre extension avec un centre de vaccination sur Lyon et il y a le message d'erreur qui défile en boucle "Impossible de cliquer sur le slot avec le titre jeu. 1 juillet "

`Object { type: "error", url: "https://www.doctolib.fr/vaccination-covid-19/lyon/vaccinatio…highlight%5Bspeciality_ids%5D%5B%5D=5494&pid=practice-163661", message: "Impossible de cliquer sur le slot avec le titre jeu. 1 juil. 11:50", location: {…}, error: {…} }`

Avez-vous une solution ? 
Merci bien d'avance.

**Comment by julienw** [comment]
Peux-tu STP nous donner quel est le centre de vaccination en question ? merci :-)

**Comment by kabarigou** [comment]
[Centre de vaccination - Palais des sports - Gerland ](https://www.doctolib.fr/vaccination-covid-19/lyon/palais-des-sports-gerland-hcl-vaccination-covid)

**Comment by julienw** [comment]
Ah, c'est amusant, je ne le trouve pas avec le moteur de recherche, mais à la place je trouve https://www.doctolib.fr/vaccination-covid-19/lyon/vaccinationhcl?highlight%5Bspeciality_ids%5D%5B%5D=5494&pid=practice-163661...

Sur celui-ci je trouve un bug, j'ai l'impression qu'on ne prend pas le bon "motif" (on prend l'injection unique au lieu de la 1re injection).

**Comment by julienw** [comment]
Pour ce bug, on peut ajouter (par exemple) un `text.includes("unique")` sur https://github.com/dunglas/vaccin.click/blob/c419dc905fa1f2aa207daee2f369f9dd86100213/content_scripts/doctolib/book.js#L87

**Comment by julienw** [comment]
Je ne suis pas sûr que ce soit lié au problème que tu rencontres mais c'est un gros souci: en effet on prend le premier rendez-vous mais pas le second...

**Comment by kabarigou** [comment]
Merci beaucoup pour votre retour ! 

Comment puis-je ajouter `text.includes("unique")` dans le code de l'extension facilement ? Merci.

**Comment by julienw** [comment]
Il faudrait que quelqu'un fasse le patch, puis que le mainteneur fasse une nouvelle version.
Mais à dire vrai, à l'heure actuelle, dans la situation de plus grande abondance de doses, c'est sans doute plus simple de prendre directement sur le site doctolib?

**Comment by kabarigou** [comment]
En effet, pour ma part, j'ai pu trouver un creneau dans une semaine en allant directement sur Doctolib.

**Comment by julienw** [comment]
J'ai fait quelques tests: je pense que ce message spécifique apparait lorsque le rendez-vous n'est déjà plus disponible au moment où on clique.
