### ISSUE TITLE
"Impossible de cliquer sur le slot"

### ISSUE THREAD

**Issue by oojdoo** [dunglas/vaccin.click#73]
Bonjour,
Vaccin clik a généré une erreur sur la détection des rdv dispo _(EDIT) mais en fin de compte quand en cliquant sur le centre l'onglet s'ouvre bien._

![Capture d’écran_2021-07-19_16-42-47](https://user-images.githubusercontent.com/30955917/126179583-a841f6b8-d67b-4e60-943d-5841473296de.png)

Erreur : _"Echec - Impossible de cliquer sur le slot avec le titre mar. 3 août"_.

Merci pour cette belle extension bien pratique!

oojdoo

**Comment by oojdoo** [comment]
C'est peut-être le match qui ne prend pas en compte l'accent circonflexe de août?

`      // format : lun. 17 mai 08:54
      const parts = slot.title.match(/([0-9]+) ([a-z]+) ([0-9]+:[0-9]+)/);
      if (!parts) {
        throw new Error(
          `Impossible de cliquer sur le slot avec le titre ${slot.title}`
        );
      }`

**Comment by julienw** [comment]
Ah, c'est bien possible!
Tu penses pouvoir essayer ce patch et valider que ça corrige l'erreur ?

**Comment by oojdoo** [comment]
Je n'ai pas programmé en java depuis pas mal de temps et j'ai tenté d'installer java sous ma debian mais c'est juste la lutte avec l'open-jdk (création de compte chez oracle), donc j'espère que quelqu'un d'autre pourra écrire le patch et le valider.

**Comment by julienw** [comment]
C'est du JavaScript ;-)
Si tu veux t'y frotter, on a une petite doc par là => https://github.com/dunglas/vaccin.click/blob/main/CONTRIBUTING.md

**Comment by oojdoo** [comment]
_C'est du JavaScript, pas besoin de java, juste nodejs ;-)_
Merci :D

_Si tu veux t'y frotter, on a une petite doc par là_ 
Super; j'ai tout installé et j'arrive à lancer l'extension via mon clone git. Donc je vais tenter de générer un patch!

**Comment by oojdoo** [comment]
J'ai donc effectué le changement suivant #https://github.com/oojdoo/vaccin.click/commit/3cc3747b79da56d3464081e7f06bd0d676b4aaf3 :

```diff
      // format : lun. 17 mai 08:54
-     const parts = slot.title.match(/([0-9]+) ([a-z]+) ([0-9]+:[0-9]+)/);
+     const parts = slot.title.match(/([0-9]+) [\p{Letter}\s]+ ([0-9]+:[0-9]+)/gu);
      if (!parts) {
        throw new Error(
          `Impossible de cliquer sur le slot avec le titre ${slot.title}`
      }
```

À présent, vaccin click ne génère plus une erreur.

![Capture d’écran_2021-07-20_08-35-37](https://user-images.githubusercontent.com/30955917/126273494-9632e9c3-91df-430f-b751-573ae685154e.png)

Mais, pour être sûr, il faudrait quand même faire des tests sur cette expression régulière : `/([0-9]+) [\p{Letter}\s]+ ([0-9]+:[0-9]+)/gu`

Est-ce quelqu'un peut tester ça?

**Comment by oojdoo** [comment]
J'ai testé cette expression régulière avec https://www.regextester.com/ et ça semble bien fonctionné.

Je fais quoi maintenant? Un pull request?

**Comment by julienw** [comment]
Je suis pas convaincu par le `\s` (qui signifie "n'importe quel caractère 'espace', tel que espace / tab / etc), l'as-tu ajouté pour une raison particulière ? Depuis le lien que tu as mis plus haut, ça permet de match des "mots avec espace", alors que sans le `\s` c'est juste "un mot" :-)

Si tu l'enlèves et que tu vérifies encore, tu pourras faire une pull request en effet :-)

**Comment by oojdoo** [comment]
#75

**Comment by julienw** [comment]
Fixed by #75, merci @oojdoo !
