### ISSUE TITLE
Doctolib.click 

### ISSUE THREAD

**Issue by benchti** [dunglas/vaccin.click#74]
c'est un ticket complètement hors sujet et à fermer sûrement immédiatement mais si un forck est fait un jour voici des specs avec une expérience d'utilisateur . 

Avec la généralisation de doctolib (c'est un fait, pas un débat) il est plus en plus facile de prendre un rendez vous, mais aussi de l'**annuler** . 

Cette semaine je viens de faire l'expérience d'un rendez vous médical : tiens je vais regarder s'il y a de la place et par chance j'ai un rendez vous dans 3 jours (généralement c'est 1 mois). Donc j'ai eu de la chance (sûrement suite à un désistement). 

Et je me suis dit tiens si j'avais eu sous la main un doctolib.click qui, pour un médecin donné m'ouvre un onglet s'il y a un rendez vous dans les X jours (suite à une annulation donc). 

Je complète ma "spec" avec mon expérience et des captures d'écran pour mon cas précis : 

Le médecin a 2 lieux de consultation je souhaite si possible n'en choisir qu'un 

![Capture d’écran du 2021-07-20 11-26-16](https://user-images.githubusercontent.com/663816/126297513-a62b161d-f4fd-4ecb-96bf-54e6565de9dc.png)

On est le 20 juillet , prochain rendez vous le 26 juillet ça peut matcher **yeah** 

![Capture d’écran du 2021-07-20 11-27-40](https://user-images.githubusercontent.com/663816/126297725-9a992aa6-ac12-45b0-b77b-0d391806b8c7.png)

Ha non ! c'est un remplaçant :( 

![Capture d’écran du 2021-07-20 11-28-56](https://user-images.githubusercontent.com/663816/126297960-9e0ecbcb-f778-42b6-bdb3-3664b11ba0e9.png)

Ok 27 aout ça match 

![Capture d’écran du 2021-07-20 11-30-48](https://user-images.githubusercontent.com/663816/126298343-fcb438aa-e04f-4a18-9eb9-1794059554b2.png)

A fermer donc ( car non je ne vais pas forcker et faire un plugin firefox) mais je voulais laisser une trace/expérience  ;) 

(et grâce à Vaccin.click je capte mieux la 5G merci)

**Comment by julienw** [comment]
Tu devrais remonter ça à doctolib ;-)



> (et grâce à Vaccin.click je capte mieux la 5G merci)

🥰
