### ISSUE TITLE
Impossible de cliquer sur le slot avec le titre jeu. 29 juil. 13:25

### ISSUE THREAD

**Issue by Clemzd** [dunglas/vaccin.click#76]
Hello,

Merci beaucoup pour cette extension, je viens de détecter un bug au moment de la réservation (book.js) lié au format de la date.

![image](https://user-images.githubusercontent.com/4448250/126348093-70626e6c-f4fb-4b87-ac3c-709ddadf8a72.png)

Dans mon cas, il y a un point après "juil" ce qui fait au final "jeu. 29 juil. 13:25"

Ca a l'air de ne pas passer

```
// format : lun. 17 mai 08:54
const parts = slot.title.match(/([0-9]+) ([a-z]+) ([0-9]+:[0-9]+)/);
```

Il faudrait gérer le point juste après le mois dans l'expression régulière

https://github.com/dunglas/vaccin.click/blob/main/content_scripts/doctolib/book.js#LC281

**Comment by oojdoo** [comment]
Salut,

En prenant en compte le PR #75 , il me semble que l'expression régulière ci-dessous devrait prendre en charge ce point : 

```diff
- const parts = slot.title.match(/([0-9]+) [\p{Letter}]+ ([0-9]+:[0-9]+)/gu);
+ const parts = slot.title.match(/([0-9]+) [\p{Letter}.]+ ([0-9]+:[0-9]+)/gu);
```

Sur https://www.regextester.com/ ça semble bien fonctionner.
Qu'en pensez-vous?

**Comment by julienw** [comment]
@oojdoo ça m'a l'air bien !

**Comment by Clemzd** [comment]
Bien vu et merci les gars !
