### ISSUE TITLE
Motif non trouvé pour le CHU de Caen

### ISSUE THREAD

**Issue by ke20** [dunglas/vaccin.click#79]
Bonjour,

J'ai un souci avec le centre de vaccination https://www.doctolib.fr/vaccination-covid-19/caen/chu-caen-vaccination-covid?highlight%5Bspeciality_ids%5D%5B%5D=5494

j'ai le message d'erreur :
```Catégorie de motif non trouvé. Motifs disponibles : Choisissez une catégorie, Personnes de plus de 12 ans, professions prioritaires, Professionnels avec obligation vaccinale```

Pourtant, j'ai cliqué sur le centre et choisit les motifs comme montré ci-dessous, mais ces derniers ne sont pas pris en compte:
![Capture d’écran de 2021-07-21 09-54-20](https://user-images.githubusercontent.com/1608482/126452878-56d56bbf-e537-49f7-b7d0-bccd32b9015c.png)

Je précise que je suis dans le sud et que j'essaie de réserver dans un CHU en Normandie, est-ce que ça peut jouer ?

**Comment by julienw** [comment]
Pas d'inquiétude, il n'y a aucun rapport avec ta localisation.

Il faut mettre à jour cette regexp: https://github.com/dunglas/vaccin.click/blob/f199f5773d2f0db7479ecec2e2bffc656230c623/content_scripts/doctolib/book.js#L110. Je regarde ça de suite.
