### ISSUE TITLE
Impossible d'ajouter un centre à ma liste

### ISSUE THREAD

**Issue by Tom32i** [dunglas/vaccin.click#8]
Hello @dunglas et merci pour cette extension :)

Petit rapport de bug : 

J'ai ajouté 24 centres à ma liste, et je ne peux plus en rajouter, le bouton "Ajouter à ma liste" sur un 25ème déclenche l'erreur suivante : 

> Error: QuotaExceededError: storage.sync API call exceeded its quota limitations.

C'est peut être normal, mais du coup j'ai un doute sur le fait que l'extension fait bien son travail (pour l'instant elle ne m'a pas proposer de créneau).

**Comment by dunglas** [comment]
L'extension utilise le stockage `sync` de Firefox qui permet de préserver la config de l'extension (la liste des centres) entre les différentes installations du navigateur (via ton compte Mozilla). 

Je n'ai pas testé avec autant de centres, peut-être qu'il faudrait utiliser le stockage classique pour avoir plus de place.

Pour voir si ça fonctionne ou pas, tu peux aller dans `about:debugging`, cliquer sur "this Firefox", trouver l'extension, cliquer sur "inspect" puis ouvrir la console. Si ça fonctionne, une erreur indiquant "aucun créneau disponible" doit être loggué régulièrement (toutes les 3 minutes) dans la console.

**Comment by dunglas** [comment]
D'après https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync#storage_quotas_for_sync_data on a que 100 ko de stockage, c'est effectivement peut-être un peu léger.

Je me demande si la synchro a un intérêt de toute façon.

**Comment by Tom32i** [comment]
Ok, merci pour les précisions.

Grace au debug je peux voir que l'extension fonctionne bien en tout cas 👍 

Je vois si j'ai le temps dans la journée pour une petite PR qui apporterai le support du local storage.

**Comment by edouardflowasia** [comment]
Hello @dunglas merci pour cette extension, super boulot.
Je viens d’être confronté au même problème: "Error: QuotaExceededError: storage.sync API call exceeded its quota limitations."

**Comment by dunglas** [comment]
Bon je crois qu'on va basculer au local storage classique. J'essaie de faire ça ce soir si personne n'a eu le temps avant !

**Comment by julienw** [comment]
Il suffit de changer `storage.sync` en `storage.local` partout où c'est présent ? (j'imagine qu'il faut migrer les données déjà stockées, on sait faire ça à l'update avec https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onInstalled)

Peut-être préfères-tu switcher vers le storage local seulement quand on dépasse la limite ? Ou ça ajoute trop de complexité ?

**Comment by dunglas** [comment]
Je pense que l'idéal serait effectivement de switcher vers le stockage local que quand `sync` est plein. Le fait de partager la config entre les ordis est quand même pratique.

**Comment by julienw** [comment]
Contre-proposition: on arrête de stocker les images, en effet le lien semble super long, je dirais environ aussi long que l'URL du centre. Donc ça ferait 2 fois plus de place ;-)

**Comment by julienw** [comment]
J'ai tenté cette approche et j'arrive à 39 centres qui peuvent être ajoutés.
