### ISSUE TITLE
Remove Moderna as default as it is restricted to be distributed to persons aged 30+ in France

### ISSUE THREAD

**Issue by hschaeidt** [dunglas/vaccin.click#82]
Does it still make sense to choose either Pfizer OR Moderna, as it will not cover the most use-cases?

Also, I realized that very often, the `option` with the Moderna injection will be above the Pfizer one.

**Comment by dunglas** [comment]
Good idea! Would you like to work on a patch?

**Comment by hschaeidt** [comment]
Resolved with https://github.com/dunglas/vaccin.click/pull/87
